# Generated by Django 5.0.1 on 2025-11-24 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('xlsx', 'Excel Spreadsheet'), ('email', 'Email'), ('other', 'Other')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parsed_content', models.TextField(blank=True, help_text='Extracted text content from the document')),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_pairs', to='analyzer.conversation')),
                ('source_documents', models.ManyToManyField(blank=True, related_name='qa_pairs', to='analyzer.document')),
            ],
            options={
                'verbose_name': 'Question & Answer',
                'verbose_name_plural': 'Questions & Answers',
                'ordering': ['-created_at'],
            },
        ),
    ]
