# Generated by Django 5.0.1 on 2025-11-24 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField(help_text='Index of this chunk within the document')),
                ('content', models.TextField(help_text='Text content of this chunk')),
                ('start_char', models.IntegerField(default=0, help_text='Starting character position')),
                ('end_char', models.IntegerField(default=0, help_text='Ending character position')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='analyzer.document')),
            ],
            options={
                'verbose_name': 'Document Chunk',
                'verbose_name_plural': 'Document Chunks',
                'ordering': ['document', 'chunk_index'],
                'unique_together': {('document', 'chunk_index')},
            },
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='source_chunks',
            field=models.ManyToManyField(blank=True, help_text='Specific chunks used to generate the answer', related_name='qa_pairs', to='analyzer.chunk'),
        ),
    ]
